abonados/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.abonados, name='abonados'),
    path('detalles/<int:id>', views.detalles, name='detalles'),
]

accounts/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

feriados/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.feriados, name='feriados'),
]

horarios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.horarios, name='horarios'),
]

paradas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.paradas, name='paradas'),
]

siscom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('vehiculos/', include('vehiculos.urls')),
    path('feriados/', include('feriados.urls')),
    path('horarios/', include('horarios.urls')),
    path('tarifas/', include('tarifas.urls')),
    path('abonados/', include('abonados.urls')),
    path('paradas/', include('paradas.urls')),
]

tarifas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tarifas, name='tarifas'),
]

vehiculos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.vehiculos, name='vehiculos'),
]

abonados/models.py
from django.db import models
from paradas.models import Parada
from siscom.choices import DESTINOS, DIAS

# Create your models here.

class Abonado(models.Model):
	nombre = models.CharField(max_length=50)
	direccion = models.CharField(max_length=50)
	telefono = models.CharField(max_length=30)
	observaciones = models.CharField(max_length=200)
	numeroAbonado = models.IntegerField()
	documento = models.CharField(max_length=45)
	localidad = models.CharField(max_length=45)
	codigoPostal = models.CharField(max_length=10)

	def __str__(self):
		return f'{self.nombre} / {self.numeroAbonado}'

class Abono(models.Model):
	idAbonado = models.ForeignKey(Abonado, on_delete=models.CASCADE)
	fechaDesde = models.DateField()
	fechaHasta = models.DateField()

	def __str__(self):
		return f'{self.idAbonado} / {self.fechaDesde.strftime("%Y-%m-%d")} / {self.fechaHasta.strftime("%Y-%m-%d")}'

class AbonadoDia(models.Model):
	idAbonado = models.ForeignKey(Abonado, on_delete=models.CASCADE)
	destino = models.CharField(max_length=4,
		choices = DESTINOS, default = 'ACAP')
	dia = models.CharField(max_length=3, choices = DIAS)
	hora = models.TimeField()
	idparada = models.ForeignKey(Parada, on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.idAbonado} / {self.destino} / {self.dia} / {self.hora}'

accounts/models.py
from django.db import models

# Create your models here.

agenda/models.py
from django.db import models

# Create your models here.

class Agenda(models.Model):
    fecha = models.DateField()
    destino = 

feriados/models.py
from django.db import models

# Create your models here.

class Feriado(models.Model):
	fecha = models.DateField()

	def __str__(self):
		return (self.fecha.strftime('%Y-%m-%d'))

horarios/models.py
from django.db import models
from siscom.choices import DESTINOS, DIAS

# Create your models here.

class Horario(models.Model):
	destino = models.CharField(max_length=4,
		choices = DESTINOS, default = 'ACAP')
	dia = models.CharField(max_length=3, choices = DIAS)
	hora = models.TimeField()

	class Meta():
		ordering = ['destino', 'dia', 'hora', ]

	def __str__(self):
		return f"{self.destino} / {self.dia} / {self.hora.strftime('%H:%M')}"

paradas/models.py
from django.db import models
from siscom.choices import DESTINOS, DIAS, PARADAS

# Create your models here.

class Parada(models.Model):
	nombre = models.CharField(max_length=50)
	orden = models.IntegerField()
	parv = models.IntegerField(choices = PARADAS, default = 0)

	def __str__(self):
		return f'{self.parv} / {self.orden} / {self.nombre}'

tarifas/models.py
from django.db import models
from siscom.choices import DESTINOS, DIAS, PARADAS

# Create your models here.

class Tarifa(models.Model):
	destino = models.CharField(max_length=4,
		choices = DESTINOS, default = 'ACAP')
	dia = models.CharField(max_length=3, choices = DIAS)
	horaDesde = models.TimeField()
	horaHasta = models.TimeField()

	class Meta():
		ordering = ['destino', 'dia', 'horaDesde', ]

	def __str__(self):
		return f'{self.destino} / {self.dia} / {self.horaDesde} / {self.horaHasta}'

vehiculos/models.py
from django.db import models
from siscom.choices import DESTINOS, DIAS, PARADAS, ESTADOS
# Create your models here.

class Vehiculo(models.Model):
	nombre = models.CharField(max_length=50)
	asientos = models.IntegerField()
	estado = models.CharField(max_length=2,
		choices = ESTADOS, default = 'OK')

	def __str__(self):
		return f'{self.nombre} / {self.asientos}'

abonados/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Abonado, Abono, AbonadoDia

# Create your views here.

def abonados(request):
	abonados = Abonado.objects.all().order_by('nombre')
	contexto = {'abonados':abonados}
	return render(request, 'abonados.html', contexto)

def detalles(request, id):
	abonados = Abonado.objects.all().filter(id=id)
	abonos = Abono.objects.all().filter(idAbonado=id).order_by('fechaDesde')
	abonadodias = AbonadoDia.objects.all().filter(idAbonado=id).order_by('destino', 'dia', 'hora')
	contexto = {'detalles':[abonados, abonos, abonadodias]}
	return render(request, 'detalles.html', contexto)

accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

agenda/views.py
from django.shortcuts import render

# Create your views here.

feriados/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Feriado

# Create your views here.

def feriados(request):
	feriados = Feriado.objects.all().order_by('fecha')
	print(feriados[0])
	contexto = {'detalles':feriados}
	return render(request, 'feriados.html', contexto)

horarios/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Horario

# Create your views here.

def horarios(request):
	horarios = Horario.objects.all().distinct().order_by('destino', 'dia', 'hora')
	contexto = {'detalles':horarios}
	return render(request, 'horarios.html', contexto)

paradas/views.py
from django.shortcuts import render
from .models import Parada

# Create your views here.

def paradas(request):
	paradas = Parada.objects.all().order_by('parv', 'orden', 'nombre')
	contexto = {'detalles':paradas}
	return render(request, 'paradas.html', contexto)

tarifas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Tarifa

# Create your views here.

def tarifas(request):
	tarifas = Tarifa.objects.all().order_by('destino', 'dia', 'horaDesde')
	contexto = {'detalles':tarifas}
	return render(request, 'tarifas.html', contexto)

vehiculos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Vehiculo

# Create your views here.

def vehiculos(request):
	vehiculos = Vehiculo.objects.all().order_by('nombre')
	contexto = {'vehiculos':vehiculos}
	return render(request, 'vehiculos.html', contexto)

abonados/templates/abonados.html
{% extends 'home.html' %}

{% block cuerpo %}

<h1>Abonados</h1>
<table class="table table-bordered y-10">
	<thead>
	  	<tr>
			<th scope="col">Nro Abonado</th>
			<th scope="col">Nombre</th>
			<th scope="col">Direccion</th>
			<th scope="col">Telefono</th>
			<th scope="col">Acciones</th>
		  </tr>
	</thead>
	<tbody>
		{% for abonado in abonados %}
		  	<tr>
				<th scope="row">{{abonado.numeroAbonado}}</th>
				<td>{{abonado.nombre}}</td>
				<td>{{abonado.direccion}}</td>
				<td>{{abonado.telefono}}</td>
				<td>
					<a href="{% url 'detalles' abonado.id %}">Detalles</a>
				</td>
				</tr>
	  	{% endfor %}
	</tbody>
  </table>
{% endblock %}

abonados/templates/detalles.html
{% extends 'home.html' %}

{% block cuerpo %}

<h3>Datos Personales</h3>
Nombre: {{detalles.0.0.nombre}} <br>
Direccion: {{detalles.0.0.direccion}} <br>
Telefono: {{detalles.0.0.telefono}} <br>
observaciones: {{detalles.0.0.observaciones}} <br>
Numero de Abonado: {{detalles.0.0.numeroAbonado}}

Documento: {{detalles.0.0.documento}} <br>
Localidad: {{detalles.0.0.localidad}} <br>
Codigo Postal: {{detalles.0.0.codigoPostal}} <br>


<br>
<h3>Abonos</h3>
<table class="table table-bordered y-10">
	<thead>
	  	<tr>
			<th scope="col">Fecha Desde</th>
			<th scope="col">Fecha Hasta</th>
		  </tr>
	</thead>
	<tbody>
		{% for abono in detalles.1 %}
		  	<tr>
				<td>{{abono.fechaDesde|date:"d-m-Y"}}</td>
				<td>{{abono.fechaHasta|date:"d-m-Y"}}</td>
			</tr>
	  	{% endfor %}
	</tbody>
  </table>

<br>

<h3>Reservas</h3>
<table class="table table-bordered y-10">
	<thead>
	  	<tr>
			<th scope="col">Destino</th>
			<th scope="col">Dia</th>
			<th scope="col">Hora</th>
		  </tr>
	</thead>
	<tbody>
		{% for abonadodia in detalles.2 %}
		{{ abono }}
		  	<tr>
				<td>{{abonadodia.get_destino_display}}</td>
				<td>{{abonadodia.get_dia_display}}</td>
				<td>{{abonadodia.hora|date:'H:i'}}</td>
			</tr>
	  	{% endfor %}
	</tbody>
  </table>

{% endblock %}

feriados/templates/feriados.html
{% extends 'home.html' %}

{% block cuerpo %}

<h1>Feriados</h1>
<table class="table table-bordered y-10">
	<thead>
	  	<tr>
			<th scope="col">Fecha</th>
		</tr>
	</thead>
	<tbody>
		{% for feriado in detalles %}
		  	<tr>
				<td scope="row">{{feriado.fecha|date:"d-m-Y"}}</td>
			</tr>
	  	{% endfor %}
	</tbody>
  </table>
{% endblock %}

horarios/templates/horarios.html
{% extends 'home.html' %}

{% block cuerpo %}

<h1>Horarios</h1>
<table class="table table-bordered y-10">
	<thead>
	  	<tr>
			<th scope="col">Destino</th>
			<th scope="col">Dia</th>
			<th scope="col">Hora</th>
		</tr>
	</thead>
	<tbody>
		{% for horario in detalles %}
		  	<tr>
				<td scope="row">{{horario.get_destino_display}}</td>
				<td scope="row">{{horario.get_dia_display}}</td>
				<td scope="row">{{horario.hora|date:'H:i'}}</td>
			</tr>
	  	{% endfor %}
	</tbody>
  </table>
{% endblock %}

paradas/templates/paradas.html
{% extends 'home.html' %}

{% block cuerpo %}

<h1>Paradas</h1>
<table class="table table-bordered y-10">
	<thead>
	  	<tr>
			<th scope="col">Rumbo</th>
			<th scope="col">Orden</th>
			<th scope="col">Nombre</th>
		</tr>
	</thead>
	<tbody>
		{% for parada in detalles %}
		  	<tr>
				<td scope="row">{{parada.get_parv_display}}</td>
				<td scope="row">{{parada.orden}}</td>
				<td scope="row">{{parada.nombre}}</td>
			</tr>
	  	{% endfor %}
	</tbody>
  </table>
{% endblock %}

tarifas/templates/tarifas.html
{% extends 'home.html' %}

{% block cuerpo %}

<h1>Tarifas</h1>
<table class="table table-bordered y-10">
	<thead>
	  	<tr>
			<th scope="col">Destino</th>
			<th scope="col">Dia</th>
			<th scope="col">Hora Desde</th>
			<th scope="col">Hora Hasta</th>
		</tr>
	</thead>
	<tbody>
		{% for tarifa in detalles %}
		  	<tr>
				<td scope="row">{{tarifa.get_destino_display}}</td>
				<td scope="row">{{tarifa.get_dia_display}}</td>
				<td scope="row">{{tarifa.horaDesde|date:'H:i'}}</td>
				<td scope="row">{{tarifa.horaHasta|date:'H:i'}}</td>
			</tr>
	  	{% endfor %}
	</tbody>
  </table>
{% endblock %}

vehiculos/templates/vehiculos.html
{% extends 'home.html' %}

{% block cuerpo %}
<h1>Vehiculos</h1>
<table class="table table-bordered y-10">
	<thead>
	  	<tr>
			<th scope="col">Nombre</th>
			<th scope="col">Asientos</th>
			<th scope="col">Estado</th>
		  </tr>
	</thead>
	<tbody>
		{% for vehiculo in vehiculos %}
		  	<tr>
				<td scope="row">{{vehiculo.nombre}}</td>
				<td>{{vehiculo.asientos}}</td>
				<td>{{vehiculo.get_estado_display}}</td>
			</tr>
	  	{% endfor %}
	</tbody>
  </table>

{% endblock %}